server:
  port: ${ESACO_BIND_PORT:8156}
  address: ${ESACO_BIND_ADDRESS:0.0.0.0}

  use-forward-headers: ${ESACO_USE_FORWARD_HEADERS:false}

spring:
  main:
    allow-bean-definition-overriding: TRUE
    
  profiles:
    active: prod

  cache:
    type: ${ESACO_CACHE:caffeine}
    cache-names: introspect,userinfo
    caffeine:
      spec: ${ESACO_CACHE_SPEC:maximumSize=500,expireAfterWrite=60s}
      
esaco:
  username: ${ESACO_USER_NAME:user}
  password: ${ESACO_USER_PASSWORD:password}
        
oidc:
  clients:
      - issuer-url: http://localhost:8080/
        client-id: password-grant
        client-secret: secret
      - issuer-url: https://iam.local.io/
        client-id: argus-oidc-client-id
        client-secret: argus-oidc-client-secret
      - issuer-url: https://iam-test.indigo-datacloud.eu/
        client-id: argus-oidc-client-id
        client-secret: argus-oidc-client-secret

x509:
  trustAnchorsDir: ${X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
  trustAnchorsBundle: ${X509_TRUST_ANCHORS_BUNDLE:/etc/ssl/certs/ca-bundle.crt}
  trustAnchorsType: ${X509_TRUST_ANCHORS_TYPE:DIR}
  trustAnchorsRefreshMsec: ${X509_TRUST_ANCHORS_REFRESH:14400}

tls:
  version: ${ESACO_TLS_VERSION:TLSv1.2}